### ISSUE TITLE
undefined function json.patch

### ISSUE THREAD

**Issue by gottkanzler-rgb** [fugue/regula#73] opened 2020-11-30 14:47 UTC
Hi there,
i recently tried to run regula with conftest. After executing the exact commands defined in documentation, i ran into the following error:

 `Error: running test: load: loading policies: get compiler: 1 error occurred: policy\regula\lib\fugue_resource_view.rego:34: rego_type_error: undefined function json.patch`

I'm getting this error on Win10 as well as Ubuntu 20.04. I'm running conftest on version 22.0.

To make sure the reason of the error is not a wrong folder structure:

policy
├── regula
│   ├── lib
│   │   ├── aws
│   │   │   └── security_group.rego
│   │   ├── azure
│   │   │   └── network_security_group.rego
│   │   ├── fugue_check_report.rego
│   │   ├── fugue.rego
│   │   ├── fugue_regula.rego
│   │   ├── fugue_resource_view.rego
│   │   ├── gcp
│   │   │   └── compute_firewall.rego
│   │   ├── util_merge.rego
│   │   └── util_resolve.rego
│   └── rules
│       ├── cloudfront_distribution_https.rego
│       ├── cloudtrail_log_file_validation.rego
│       ├── ebs_volume_encrypted.rego
│       ├── iam_admin_policy.rego
│       ├── iam_user_attached_policy.rego
│       ├── kms_rotate.rego
│       ├── s3_bucket_sse.rego
│       ├── security_group_ingress_anywhere_rdp.rego
│       ├── security_group_ingress_anywhere.rego
│       ├── security_group_ingress_anywhere_ssh.rego
│       └── vpc_flow_log.rego
└── regula.rego

Could you please help me understand root cause of this issue.

**Comment by MatthiasScholzTW** [comment] 2020-12-03 18:21
I can confirm experiencing the same issue using opa 0.24.0.

Looking at the opa version used in the ci examples points to 0.15.1 the latest opa version is 0.24.0.

- https://github.com/fugue/regula-action/blob/e334326f6392686f8516d80782c97c897979f2aa/Dockerfile#L8

It seems regula did not kept up the pace of opa.

**Comment by jaspervdj-luminal** [comment] 2020-12-03 18:33
Thanks for reporting this! The development version of `regula` (i.e. `master`) is using `json.patch` which is a new builtin that will be introduced in `opa-v0.25.x`.  In the CI for this repository, we're using the `master` branch of `opa` for that purpose.

Once the new `opa` version is out, a new `regula` version will be released as well.  So until then there are two options:

 -  Use `regula-v0.5.0` with any `opa` more recent than `v0.15.1`
 -  Use `regula-master` with `opa-master`

Hope this helps!

**Comment by jaspervdj-luminal** [comment] 2020-12-18 11:32
`opa-v0.25.x` is now released so I'm closing this issue as everything should work fine again if you use the releases.

**Closed by jaspervdj-luminal** 2020-12-18 11:32 UTC

**Comment by marc181982** [comment] 2020-12-19 21:40
Tried the first option: _Use regula-v0.5.0 with any opa more recent than v0.15.1_

But it's not working, running into the same issues mentioned by the topic starter.

          name: regula-install
          command: |
            wget -O regula.tar.gz https://github.com/fugue/regula/archive/v0.5.0.tar.gz
            sudo mkdir -p /opt/regula
            sudo tar -xf regula.tar.gz --strip-components=1 -C /opt/regula
            rm regula.tar.gz
      - run:
          name: opa-install
          command: |
            wget -O opa https://github.com/open-policy-agent/opa/releases/download/v0.25.2/opa_linux_amd64
            chmod +x opa
            sudo mkdir -p /usr/local/bin
            sudo mv opa /usr/local/bin

**Comment by jaspervdj-luminal** [comment] 2020-12-21 13:43
@marc181982 I'm not sure what the problem is, it seems like things should work from what I can see in those versions.  I would need some more information (e.g. how exactly you're invoking OPA, and the exact error message) to be able to tell what's wrong.

**Comment by christophetd** [comment] 2020-12-22 13:22
Hello @jaspervdj-luminal, 

I have the same issue and I can confirm on a **clean Docker Ubuntu 18.04 install** that it's broken, see steps below to reproduce.

```
christophe@laptop:$ docker run --rm -it ubuntu:18.04

apt update -y && apt install -y git wget nano
# Install OPA
wget https://github.com/open-policy-agent/opa/releases/download/v0.25.2/opa_linux_amd64 -O /usr/local/bin/opa
chmod +x /usr/local/bin/opa
# Install conftest
wget https://github.com/open-policy-agent/conftest/releases/download/v0.22.0/conftest_0.22.0_linux_amd64.deb
dpkg -i conftest_0.22.0_linux_amd64.deb

# Set up fugue
conftest pull -p policy/ github.com/fugue/regula/conftest
conftest pull -p policy/regula/lib github.com/fugue/regula/lib

# Sample rules
conftest pull -p rules github.com/fugue/regula/rules/aws


# Sample TF plan (a single s3 bucket)
cat > plan.json <<EOF
{"format_version":"0.1","terraform_version":"0.13.5","planned_values":{"root_module":{"resources":[{"address":"aws_s3_bucket.sample","mode":"managed","type":"aws_s3_bucket","name":"sample","provider_name":"registry.terraform.io/hashicorp/aws","schema_version":0,"values":{"acl":"private","bucket":"my-sample-bucket","bucket_prefix":null,"cors_rule":[],"force_destroy":false,"grant":[],"lifecycle_rule":[],"logging":[],"object_lock_configuration":[],"policy":null,"replication_configuration":[],"server_side_encryption_configuration":[],"tags":null,"website":[]}}]}},"resource_changes":[{"address":"aws_s3_bucket.sample","mode":"managed","type":"aws_s3_bucket","name":"sample","provider_name":"registry.terraform.io/hashicorp/aws","change":{"actions":["create"],"before":null,"after":{"acl":"private","bucket":"my-sample-bucket","bucket_prefix":null,"cors_rule":[],"force_destroy":false,"grant":[],"lifecycle_rule":[],"logging":[],"object_lock_configuration":[],"policy":null,"replication_configuration":[],"server_side_encryption_configuration":[],"tags":null,"website":[]},"after_unknown":{"acceleration_status":true,"arn":true,"bucket_domain_name":true,"bucket_regional_domain_name":true,"cors_rule":[],"grant":[],"hosted_zone_id":true,"id":true,"lifecycle_rule":[],"logging":[],"object_lock_configuration":[],"region":true,"replication_configuration":[],"request_payer":true,"server_side_encryption_configuration":[],"versioning":true,"website":[],"website_domain":true,"website_endpoint":true}}}],"configuration":{"root_module":{"resources":[{"address":"aws_s3_bucket.sample","mode":"managed","type":"aws_s3_bucket","name":"sample","provider_config_key":"aws","expressions":{"acl":{"constant_value":"private"},"bucket":{"constant_value":"my-sample-bucket"}},"schema_version":0}]}}}
EOF

# Evaluate rules against sample TF plan
conftest test plan.json -p policy/ -p rules/
 ```

Output:

```
Error: running test: load: loading policies: get compiler: 3 errors occurred:
policy/regula/lib/fugue_resource_view.rego:33: rego_type_error: undefined function json.patch
policy/regula/lib/fugue_resource_view.rego:110: rego_type_error: undefined function json.patch
policy/regula/lib/fugue_resource_view.rego:259: rego_type_error: undefined function json.patch
```

**Comment by jaspervdj-luminal** [comment] 2020-12-22 15:31
@christophetd You're right -- the issue is that `master` conftest doesn't work with `master` Regula until a new version is released that has the new OPA.

In retrospect, it seems like a mistake to just use master in the examples rather than a fixed release.  Maybe you can use something like this:

```bash
# Set up fugue
REGULA_VERSION=v0.5.0
conftest pull -p policy/ "github.com/fugue/regula//conftest?ref=$REGULA_VERSION"
conftest pull -p policy/regula/lib "github.com/fugue/regula//lib?ref=$REGULA_VERSION"

# Sample rules
conftest pull -p rules "github.com/fugue/regula//rules/aws?ref=$REGULA_VERSION"
```

We'll also update the documentation to include this.
