### ISSUE TITLE
Scanning Directories using Docker Image

### ISSUE THREAD

**Issue by Lingom-KSR** [fugue/regula#155] opened 2021-08-02 12:27 UTC
Hi,
I just try to scan my directory which has terraform script file named "s3.tf"; I used the following command from Regula [docs](https://regula.dev/usage.html#running-regula-locally)

`docker run --rm -t \ -v C:\Users\Lingom\Documents\Projects\vulnado:/workspace \ --workdir /workspace \ fugue/regula:v1.0.0 run template2.yaml tfdirectory1`

When run this command getting an error saying;

**"_docker: invalid reference format._"**

Can anyone help me on this. Thank You!

**Comment by jason-fugue** [comment] 2021-08-02 17:33
Hi, @Lingom-KSR! The example `docker run` command in the documentation was written with Linux and MacOS in mind. The error you're seeing is caused by the `\`s in that command. The PowerShell equivalent is the ` (backtick) character. Either of these should work for Windows / PowerShell. On a single line:

```
docker run --rm -t -v C:\Users\Lingom\Documents\Projects\vulnado:/workspace --workdir /workspace fugue/regula:v1.0.0 run template2.yaml tfdirectory1
```

Or split into multiple lines:

```
docker run --rm -t `
-v C:\Users\Lingom\Documents\Projects\vulnado:/workspace `
--workdir /workspace `
fugue/regula:v1.0.0 run template2.yaml tfdirectory1
```

**Comment by ameliafugue** [comment] 2021-08-09 16:31
@Lingom-KSR Did the instructions above resolve your issue? 

We’ll close this ticket in 7 days if we don’t hear back.

**Closed** 2021-09-07 17:56 UTC
