### ISSUE TITLE
Error in tag_all_resources

### ISSUE THREAD

**Issue by jmcgill** [fugue/regula#107] opened 2021-05-13 16:22 UTC
When running the regula rules against the output of plan for our terraform, I receive the following error:

```
{
  "errors": [
    {
      "message": "functions must not produce multiple outputs for same inputs",
      "code": "eval_conflict_error",
      "location": {
        "file": "/Users/jmcgill/src/regula/examples/aws/tag_all_resources.rego",
        "row": 77,
        "col": 1
      }
    }
  ]
}
```

**Comment by jason-fugue** [comment] 2021-05-13 16:49
Thanks for opening this issue! I think I've got a fix in this PR: https://github.com/fugue/regula/pull/108

If you don't mind, could you please checkout that branch and see if it resolves that error?

**Comment by jmcgill** [comment] 2021-05-13 16:58
Confirmed that the branch fixes the issue; thank you for the very prompt fix!

I'm curious what the root issue was here - did the previous implementation assume a single tag per resource?

**Comment by jason-fugue** [comment] 2021-05-13 17:01
No problem! For the root cause - this is an example rule that's looking for tag values that are under 6 characters. The way it was written, it only accounted for one failing tag value per resource.

**Comment by ameliafugue** [comment] 2021-05-14 16:02
Closing this as the question was answered.

**Closed** 2021-05-14 16:01 UTC
